# -*- coding: utf-8 -*-
"""RealEllipse_S2-Sgtr.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r_3iXt5E4IfWveW_3AVPxKlb5cBBKe6y
"""

!pip install lsq-ellipse==2.0.1

import numpy as np
from ellipse import LsqEllipse
import matplotlib.pyplot as plt
from matplotlib.patches import Ellipse
import pandas as pd
from scipy.ndimage import  rotate

cm = plt.cm.get_cmap('RdYlBu')

#datos = pd.read_csv("Datos_galaxias.csv")
#print(datos)

X = [0.104,0.097,0.087,0.075,0.077,0.052,0.036,0.022,0,-0.013,-0.026,-0.013,0,0.009,0.032,0.037,0.072,0.077,0.081]
Y = [-0.166,-0.189,-0.192,-0.197,-0.193,-0.183,-0.167,-0.156,-0.103,-0.113,-0.068,0.003,0.016,0.023,0.016,0.009,-0.024,-0.03,-0.036]
dX = [0.003,0.003,0.002,0.007,0.002,0.004,0.001,0.004,0.002,0.003,0.002,0.005,0.016,0.003,0.002,0.002,0.001,0.002,0.002]
dY = [0.004,0.004,0.003,0.01,0.003,0.006,0.003,0.006,0.003,0.004,0.003,0.007,0.004,0.005,0.003,0.003,0.002,0.002,0.002]
Año = [1992.226,1994.321,1995.531,1996.256,1996.428,1997.543,1998.365,1999.465,2000.474,2000.523,2001.502,2002.252,2002.334,2002.408,2002.575,2002.65,2003.214,2003.353,2003.454]
XY = np.array(list(zip(X, Y)))

reg = LsqEllipse().fit(XY)

centro, a, b, angulo_rotado = reg.as_parameters()

print(f'centro = ( {centro[0]*41:.3f} día luz, {centro[1]*41:.3f} día luz)')
print(f'a = {a*41:.3f} día luz')
print(f'radio = {b*41:.3f} día luz')
print(f'angulo = {np.rad2deg(angulo_rotado):.3f} rad')

fig = plt.figure(figsize=(8, 8))
ax = plt.subplot()
ax.axis('equal')
ax.errorbar(X,Y,xerr=dX,yerr=dY, linestyle="None")
ax.plot(0,0,'o',color = 'red')
sc=ax.scatter(X, Y, c=Año,cmap=cm,label="datos")
ellipse = Ellipse(
        xy=centro, width=2*a, height=2*b, angle=np.rad2deg(angulo_rotado),
        edgecolor='b', fc='None', lw=0.5, label='Fit', zorder=2)
ax.add_patch(ellipse)
plt.colorbar(sc)
plt.errorbar(X,Y,xerr=dX,yerr=dY, linestyle="None")
plt.xlabel("x (arcsec)")
plt.ylabel("y (arcsec)")